# Generated by Django 5.1.4 on 2025-02-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Payment is on pending'), ('completed', 'Payment completed successfully'), ('refunded', 'Payment refunded'), ('reversed', 'Payment reversed'), ('failed', 'Payment failed/cancelled')], default='pending', max_length=9),
        ),
    ]
